###################################
# Author by: Mr.Tr3v!0n           #
# Team : Black Coder Crush        #
# Di buat : Selasa, 16 April 2019 #
# Selesai Jam : 10:3              #
###################################
# Hanya seorang anak biasa yang gk bisa apa2😢 selalu tersakiti nolep 
# gk pernah ada yg bisa mengerti dgn perasaan ku gmn baik itu org tua😢

z="
";nBz='b}  ';bCz='b}AL';GCz='fed$';fBz='h} '\''';XCz='p}[$';FBz='   |';dBz=' _  ';lBz=' 1__';wBz='}@am';yz='|  _';QCz=' ]  ';YBz=' . |';ZCz='${p}';dCz='RATO';RCz='  ${';SBz='k}══';cz='echo';Uz='m1="';aBz='} .-';Hz='32;1';Nz='35;1';GBz='__| ';jBz='${h}';Yz='hi="';hBz='} |_';gBz='---'\''';RBz='}<${';BBz='  _|';kBz=' |  ';pBz='_${h';IBz='._|_';qz='----';jz='   _';JBz='__|_';sz='.-| ';TCz='--'\''"';DCz='p1} ';FCz='Modi';PBz='${m}';Fz='31;1';QBz='X${h';Mz='c="\';nz='h} |';Gz='h="\';wz='.  |';aCz='] ${';Qz='[36;';YCz='{m}+';pz='${b}';xz='___|';ez='h}  ';PCz='rush';WBz='_"';Vz='[38;';LCz=' [ B';fCz=']"';eCz='R ${';Ez='m="\';tz=' |_|';yBz='ab ]';Pz='\033';SCz='h}'\''-';UCz='k}<═';JCz='!0n ';HBz='|___';VCz='═══>';az='clea';vBz='${p1';uz='__.-';gz='___$';mz='  "';Wz='p="\';ACz='   $';bBz='-${h';Cz='30;1';NBz='═══$';oBz='|__|';HCz='}Mr.';kz='_   ';ECz='  [ ';dz=' "${';rBz='p1}[';ABz='  | ';xBz='silt';XBz='::..';qBz='}|__';VBz='  __';Zz='[40;';EBz='|"';iBz='|   ';cCz='L OP';CCz='"';DBz='_ --';Rz='1m"';bz='r';Sz='p1="';vz='."';KCz=']   ';sBz=' Aut';ZBz=' ${b';BCz='{h}|';Lz='34;1';UBz='}   ';Iz='k="\';Dz='m"';CBz='  |_';TBz=' ${h';lz='__  ';Xz='39;1';tBz='hor$';Jz='33;1';MCz='lack';LBz='${k}';NCz=' Cod';uBz='{m}:';OCz='er C';Kz='b="\';hz='{b} ';oz='   .';fz='____';MBz='════';mBz='_|"';cBz='}|  ';rz='.---';Tz='[37;';Bz='033[';WCz=' "  ';Az='a="\';KBz=':  1';Oz='pu="';iz='    ';OBz='{h}>';ICz='Tr3v';eBz=' |"';
eval "$Az$Bz$Cz$Dz$z$Ez$Bz$Fz$Dz$z$Gz$Bz$Hz$Dz$z$Iz$Bz$Jz$Dz$z$Kz$Bz$Lz$Dz$z$Mz$Bz$Nz$Dz$z$Oz$Pz$Qz$Rz$z$Sz$Pz$Tz$Rz$z$Uz$Pz$Vz$Rz$z$Wz$Bz$Xz$Dz$z$Yz$Pz$Zz$Rz$z$az$bz$z$cz$z$cz$dz$ez$fz$gz$hz$iz$iz$jz$kz$lz$mz$z$cz$dz$nz$jz$oz$pz$qz$rz$sz$tz$uz$qz$vz$z$cz$dz$nz$wz$xz$pz$jz$yz$ABz$BBz$CBz$DBz$EBz$z$cz$dz$nz$wz$FBz$pz$GBz$HBz$IBz$xz$JBz$fz$EBz$z$cz$dz$nz$KBz$FBz$iz$LBz$MBz$NBz$OBz$PBz$QBz$RBz$SBz$MBz$TBz$UBz$VBz$fz$WBz$z$cz$dz$nz$XBz$YBz$iz$iz$ZBz$aBz$qz$rz$qz$bBz$cBz$dBz$eBz$z$cz$dz$fBz$qz$gBz$iz$iz$ZBz$hBz$DBz$iBz$iz$jBz$kBz$lBz$mBz$z$cz$dz$nBz$iz$iz$iz$iz$CBz$fz$oBz$JBz$pBz$qBz$lz$eBz$z$cz$dz$rBz$sBz$tBz$uBz$vBz$wBz$xBz$yBz$iz$iz$iz$ACz$BCz$KBz$FBz$CCz$z$cz$dz$DCz$ECz$FCz$GCz$uBz$vBz$HCz$ICz$JCz$KCz$iz$ACz$BCz$XBz$YBz$CCz$z$cz$dz$DCz$iz$iz$LCz$MCz$NCz$OCz$PCz$QCz$RCz$SCz$qz$TCz$z$cz$dz$UCz$MBz$MBz$MBz$MBz$MBz$MBz$MBz$MBz$MBz$MBz$VCz$iz$iz$iz$CCz$z$cz$WCz$iz$iz$RCz$XCz$YCz$ZCz$aCz$bCz$cCz$dCz$eCz$XCz$YCz$ZCz$fCz" 