###################################
# Author by: Mr.Tr3v!0n           #
# Team : Black Coder Crush        #
# Di buat : Selasa, 16 April 2019 #
# Selesai Jam : 10:3              #
###################################
# Hanya seorang anak biasa yang gk bisa apa2😢 selalu tersakiti nolep 
# gk pernah ada yg bisa mengerti dgn perasaan ku gmn baik itu org tua😢


z="
";kBz='h} '\''';TCz='[${p';xCz=']"';dBz=' . |';Kz='b="\';FBz='p1}V';Oz='pu="';TBz='{h}>';fBz='} .-';uBz='_${h';cCz='--'\''"';CBz='  |_';DCz='silt';jCz='1716';gBz='-${h';sCz='] ${';fz='____';Bz='033[';nz='h} |';SBz='═══$';tCz='b}AL';ez='h}  ';pBz=' |  ';gz='___$';Fz='31;1';Gz='h="\';Az='a="\';RBz='════';Hz='32;1';tz=' |_|';aCz='  ${';HCz='{h}|';Vz='[38;';JCz='m}  ';mCz='k}<═';hCz='}083';kCz='6${m';jBz=' |"';Zz='[40;';vCz='RATO';vz='."';ECz='ab $';wz='.  |';mz='  "';Jz='33;1';XBz='k}══';pz='${b}';rz='.---';KCz=' [ $';vBz='}|__';cz='echo';DBz='_ --';WBz='}<${';oz='   .';ABz='  | ';nBz='|   ';GBz='ersi';VCz='lack';ZBz='}   ';PBz=':  1';eBz=' ${b';Sz='p1="';nCz='═══>';tBz='|__|';BCz='{m}:';JBz='   |';Yz='hi="';xz='___|';Pz='\033';LBz='|___';WCz=' Cod';Cz='30;1';hz='{b} ';qBz=' 1__';GCz='   $';Qz='[36;';NBz='__|_';yBz='}Aut';lz='__  ';eCz=' Kon';ICz='"';rCz='${p}';yz='|  _';qz='----';QCz='!0n$';PCz='Tr3v';uz='__.-';Ez='m="\';oCz=' "  ';sz='.-| ';MBz='._|_';BBz='  _|';iBz=' _  ';xBz='${p1';iz='    ';Dz='m"';Iz='k="\';kz='_   ';rBz='_|"';Wz='p="\';qCz='{m}+';ZCz=' ]  ';lBz='---'\''';Tz='[37;';dCz='   [';NCz='fed$';CCz='}@am';jz='   _';gCz='Wa $';YBz=' ${h';FCz='{m}]';IBz='2"';hBz='}|  ';UBz='${m}';EBz='| ${';aBz='  __';iCz='8790';oBz='${h}';Uz='m1="';pCz='p}[$';wBz='m}[ ';Nz='35;1';SCz=']   ';OBz='|"';az='clea';uCz='L OP';Lz='34;1';QBz='${k}';KBz='__| ';LCz='{p1}';bBz='_"';UCz='1} B';OCz='}Mr.';bCz='h}'\''-';Mz='c="\';mBz='} |_';lCz='} ]"';Xz='39;1';fCz='tak ';bz='r';VBz='X${h';cBz='::..';YCz='rush';dz=' "${';ACz='hor$';sBz='b}  ';Rz='1m"';wCz='R ${';RCz='{m} ';HBz=': 1.';XCz='er C';MCz='Modi';
eval "$Az$Bz$Cz$Dz$z$Ez$Bz$Fz$Dz$z$Gz$Bz$Hz$Dz$z$Iz$Bz$Jz$Dz$z$Kz$Bz$Lz$Dz$z$Mz$Bz$Nz$Dz$z$Oz$Pz$Qz$Rz$z$Sz$Pz$Tz$Rz$z$Uz$Pz$Vz$Rz$z$Wz$Bz$Xz$Dz$z$Yz$Pz$Zz$Rz$z$az$bz$z$cz$z$cz$dz$ez$fz$gz$hz$iz$iz$jz$kz$lz$mz$z$cz$dz$nz$jz$oz$pz$qz$rz$sz$tz$uz$qz$vz$z$cz$dz$nz$wz$xz$pz$jz$yz$ABz$BBz$CBz$DBz$EBz$FBz$GBz$HBz$IBz$z$cz$dz$nz$wz$JBz$pz$KBz$LBz$MBz$xz$NBz$fz$OBz$z$cz$dz$nz$PBz$JBz$iz$QBz$RBz$SBz$TBz$UBz$VBz$WBz$XBz$RBz$YBz$ZBz$aBz$fz$bBz$z$cz$dz$nz$cBz$dBz$iz$iz$eBz$fBz$qz$rz$qz$gBz$hBz$iBz$jBz$z$cz$dz$kBz$qz$lBz$iz$iz$eBz$mBz$DBz$nBz$iz$oBz$pBz$qBz$rBz$z$cz$dz$sBz$iz$iz$iz$iz$CBz$fz$tBz$NBz$uBz$vBz$lz$jBz$z$cz$dz$wBz$xBz$yBz$ACz$BCz$xBz$CCz$DCz$ECz$FCz$iz$iz$iz$GCz$HCz$PBz$JBz$ICz$z$cz$dz$JCz$KCz$LCz$MCz$NCz$BCz$xBz$OCz$PCz$QCz$RCz$SCz$iz$GCz$HCz$cBz$dBz$ICz$z$cz$dz$JCz$iz$TCz$UCz$VCz$WCz$XCz$YCz$UBz$ZCz$iz$aCz$bCz$qz$cCz$z$cz$dz$JCz$iz$dCz$QBz$eCz$fCz$gCz$BCz$eBz$hCz$iCz$jCz$kCz$lCz$z$cz$dz$mCz$RBz$RBz$RBz$RBz$RBz$RBz$RBz$RBz$RBz$RBz$nCz$iz$iz$iz$ICz$z$cz$oCz$iz$iz$aCz$pCz$qCz$rCz$sCz$tCz$uCz$vCz$wCz$pCz$qCz$rCz$xCz" 